### PR TITLE
Meta Tags, OpenGraph and Twitter Cards

### LINKED ISSUE #546: Meta Tags, OpenGraph and Twitter Cards
Wouldn't it be nice, if the ponylang sites had OpenGraph and such? This could be done via the [meta plugin](https://mrkeo.github.io/reference/meta-tags/) ([squidfunk docs](https://squidfunk.github.io/mkdocs-material/plugins/meta/), [Python Markdown docs](https://python-markdown.github.io/extensions/meta_data/)) and by [extending the theme](https://mrkeo.github.io/customization/#extending-the-theme).

### PR DESCRIPTION
**Pull request by shaedrich**
Fixes #546

### CODE REVIEW

**Comment by shaedrich** [comment]
Result: 😍 
grafik

**Comment by SeanTAllen** [comment]
One of my favorite things about when we moved from the Hugo theme I did that supported meta tags and twitter cards was that we didn't have to try to come up with descriptions for every page. It was a slog in some cases. 

We will discuss at sync and perhaps other maintainers will see the value. I personally have been down the road of this already with our old setup and I didn't see the value in it. It was just extra work, extra stuff to maintain so I'm not in favor, but others might be. 

Will update further after our next sync call.

Thanks for opening this PR Sebastian. Your commit to improving the tutorial has been impressive and inspiring to watch as the updates flow into my inbox.

**Comment by shaedrich** [comment]
> One of my favorite things about when we moved from the Hugo theme I did that supported meta tags and twitter cards was that we didn't have to try to come up with descriptions for every page. It was a slog in some cases.

You unfortunaly see it from a slightly "wrong" angle. I totally see, that you don't want to write these descriptions. But I wouldn't call a SSG engine "better" when it is lacking a fairly standard feature, just because I personally don't like the work that goes into it and I, unlike many other people, don't use that feature.

Sorry if I'm out of line here.

**Comment by shaedrich** [comment]
> Can the title come from the H1 in the page? Having in metadata, it could get out of sync.

It _could_. However, as you see, this works fine on page but less so more often than not taken out of context as it will be when sent as a link.

**Comment by SeanTAllen** [comment]
> It _could_. However, as you see, this works fine on page but less so more often than not taken out of context as it will be when sent as a link.

Can it come from the existing breadcrumb stuff in mkdocs?

**Comment by jemc** [comment]
I'm in agreement with @SeanTAllen on this point.

I admit that having page-specific information in the Card can be useful for someone glancing quickly card but it's a fairly small amount of value and I don't think it outweighs the maintenance effort being added.

Here are my concrete set of concerns:
- the problem of drift between in the title in the metadata vs the title in the H1
- the problem of drift between chapter title in the metadata vs the actual title of the containing chapter
- the problem where all these meta fields are hidden during normal browsing, and someone may not notice that they need to update them when only looking at the static site in the netlify preview.
- the description copy, being hidden may not get as much attention as it perhaps should during maintenance

Some alternative ideas discussed in sync:
- try to pull the title info from the H1 and the chapter title, instead of duplicating that info
- use a generic description for the entire tutorial, or perhaps a per-chapter description as a compromise.

**Comment by shaedrich** [comment]
> > It _could_. However, as you see, this works fine on page but less so more often than not taken out of context as it will be when sent as a link.
> 
> Can it come from the existing breadcrumb stuff in mkdocs?

Can you elaborate on using this breadcrumb stuff? I'm not sure how I would tackle this, using pre-existing data

**Comment by shaedrich** [comment]
See https://github.com/ponylang/pony-tutorial/issues/546#issuecomment-2189685936

**Pull request closed without merging**
