### PR TITLE
fix env.vars to public field instead of method

### PR DESCRIPTION
**Pull request by erip**
Correct as of ponyc 0.25.0

### CODE REVIEW

**Comment by SeanTAllen** [comment]
@erip build failure is a problem with gitbook. i'm in the process of migrating off on a branch. I've marked this as "do not merge" for now until that work is done.

**Comment by SeanTAllen** [comment]
@erip can you rebase this against master and make sure it is working? we've moved over from gitbook to hugo.

**Comment by erip** [comment]
LGTM 👍

**Comment by SeanTAllen** [comment]
Thanks @erip

**Pull request merged**
