### PR TITLE
Replace "Wombat" in Rodent interface example

### PR DESCRIPTION
**Pull request by modernserf**
- Wombats are marsupials, not rodents, as they do not satisfy IRL rodents' placental interface. Replaced with Porcupine, an equally large and charismatic critter that is also a true rodent.
- Also, fixed apparent typo in same line: `Array[Rodent` => `Array[Rodent]`

### CODE REVIEW

**Comment by georgemarrows** [comment]
+1

As a stickler for taxonomical correctness, I support this important pull-request ;-)
The issue is covered in detail in https://answers.yahoo.com/question/index?qid=20120325192414AABNjOS

Alternative fix: change 'Rodent' to 'Mammal'

**Comment by jemc** [comment]
Given that `Wombat` is also used in many other examples in the tutorial, I think I'd prefer @georgemarrows' alternative fix of retaining `Wombat` and using `Mammal` instead of `Rodent`.

**Comment by aturley** [comment]
I'm also onboard with retaining Wombat since it appears throughout the documentation. @modernserf, any thoughts?

**Comment by modernserf** [comment]
Closing this PR in favor of #136.

**Pull request closed without merging**
