### PR TITLE
 Difference in assignation between variable and field

### PR DESCRIPTION
**Pull request by gwelr**
My tests have shown that assignation works a bit differently between variables and fields. This is what I'm trying to explained in this update of the field section of the tutorial. Also, I've put a bunch of example because I find the tutorial usually miss examples. And sometimes, nothing beats a good example for understanding :)

### CODE REVIEW

**Comment by EpicEric** [comment]
Duplicate of #274?

**Comment by gwelr** [comment]
Well, #274 is supposed to explain that `let`variables have to be assigned immediatly while #275  is supposed to explain the difference in assignment that exists between variables and fields. I'm not an expert of github commit/merge and so one so I'm not able to tell whether #275  is included in my #274 PR or not. If it is, apologize, do not hesitate to reject this PR

**Comment by Praetonus** [comment]
Yes, it looks like this PR is included in #274.

**Comment by mfelsche** [comment]
Please fix conflicts and remove duplications with #274 which is already merged.

**Comment by SeanTAllen** [comment]
Closing this as its been open for a long time with no movement and I think this is covered mostly already. Please reopen if I am incorrect.

**Pull request closed without merging**
