### PR TITLE
Re-enable htmlproofer

### PR DESCRIPTION
**Pull request by rhagenson**
Re-enabling this locally produced the following error so I am looking to see if there are any issues with building on Netlify.

```error
ERROR   -  Error building page 'expressions/variables.md': https://github.com/ponylang/pony-tutorial/: 429
```

### CODE REVIEW

**Comment by rhagenson** [comment]
Similar error on Netlify:

```error
ERROR   -  Error building page 'getting-started/index.md': https://github.com/ponylang/pony-tutorial/edit/main/docs/getting-started/index.md: 429
```

I do not yet know what is causing the issue so am investigating further now.

**Comment by rhagenson** [comment]
@SeanTAllen What are your thoughts on adding the following to `mkdocs.yml`?

```yaml
  - htmlproofer:
      raise_error: True
      raise_error_excludes: [429, 'https://github.com/']
```

This will ignore the too many requests code (429) for links back to GitHub.

**Comment by SeanTAllen** [comment]
Sounds good.

**Comment by SeanTAllen** [comment]
@rhagenson it would be nice if htmlproofer had rate limiting but ya do what ya can do.

**Comment by rhagenson** [comment]
@SeanTAllen Looks like that fixed the issue. A rate limiter would be nice. The rate of requests is pretty high to GitHub as it runs a request back for each page to the corresponding edit address.

**Comment by rhagenson** [comment]
Correction, it hits GitHub 4 times for every page on the Tutorial.

1. GitHub star/fork statistics outer box
2. GitHub star/fork statistics inner box
3. The edit address per page
4. The GitHub link in the footer

Not sure we can do anything about the star/fork box duplication and I do not want to turn off the edit addresses, however the GitHub link in the footer seems perhaps unnecessary given we have the GitHub stats now.

**Comment by SeanTAllen** [comment]
The github link in the footer is to a different repo.

What's interesting is I didn't have this issue with patterns. Not sure what is up with that. I think it must be the number of times you pushed in a given time period?

**Comment by rhagenson** [comment]
I think it is the relative size of Patterns and Tutorial. The latter has far more pages so results in far more requests.

Short of a rate limiter, maintaining a set of validated URLs would significantly improve runtime and fix potential 429 errors. May look into getting such a fix in mkdocs-htmlproofer-plugin.

**Comment by manuzhang** [comment]
@rhagenson This is the author of mkdocs-htmlproofer-plugin. Could you please create an issue at https://github.com/manuzhang/mkdocs-htmlproofer-plugin/issues ?

**Pull request merged**
