### PR TITLE
Made example compile + typo fixed

### PR DESCRIPTION
**Pull request by civ**
- ref example did not compile https://gist.github.com/ponylang-gist/2a7ccf4e3667f06f4a6ad666ee643f26 
- typo in variable name used fixed

### CODE REVIEW

**Comment by civ** [comment]
maybe add a comment on the added ref at the get method, as val did not need to be there for the get in the previous example?

**Comment by mfelsche** [comment]
Thanks for making this work! :)

Changing the get method to ref is actually not what a `getter` method should need, as it does not change the state of the class and it should not be allowed to.
To make this compile, it should actually be:

```pony
fun get(): this->String ref => _c
```

It should use an Arrow type. This is also introduced further below. I think that actually the example is a bit off here.

**Comment by civ** [comment]
That's why I avoided the arrow type there, as it's explained below like you said... 
I just put the ref there so everything in that constructed ref-example is ref

**Comment by civ** [comment]
`fun get(): String ref => _c.clone()`
works, too, but I don't know why ^^
Is that an option?

**Comment by mfelsche** [comment]
That is indeed an option. 

Another one, which i would prefer, would be to make the return tzpe of `get` a `String box` and add a stance that this needs to be box because this is how the method sees the field `_c`. This would comply with the example, being a simple container.

Or we need to somehow rewrite the narrative of this example, to introduce the arrow type here already.

**Comment by civ** [comment]
I hope I got you right there, I don't understand the capabilities. So is this roughly what you had in mind? 

https://github.com/ponylang/pony-tutorial/compare/master...civ:patch-2?short_path=a319a7b#diff-a319a7b9efaed94c6968b9e97169ccd5

If it is, I'll open a new pull request and we discard this one?
(I put this in a new branch, I don't know how to squash commits, I made these changes in the browser on github.com)

**Comment by mfelsche** [comment]
Closing this in favor of #318 .

Again, sorry for handling this in such an awful way.
Your contribution was very valuable to understanding how to improve this part of the tutorial.
Thank you!

**Pull request closed without merging**
